### ISSUE TITLE
图片好像都挂掉了。。。看不到好纠结。

### ISSUE THREAD

**Issue by lancelau4** [luke0922/the-way-to-flask#5]

**Comment by liuliqiang** [comment]
@LanceNTJH   感谢你的反馈，确实在 Github 上看是图片挂掉了。原因是我移动了 md 的文件目录，忘记将图片目录移位了，晚些时候我将会提交一次。
当然，如果你愿意尝试解决一下的话，不妨提交个 pr。
在线版本不受影响：http://www.liuliqiang.info/book/
感谢你的支持～～
